export const MODULE_ITEMS_FETCH = 'MODULE_ITEMS_FETCH'
export const MODULE_ITEMS_FETCH_SUCCESS = 'MODULE_ITEMS_FETCH_SUCCESS'
export const MODULE_ITEMS_FETCH_FAILURE = 'MODULE_ITEMS_FETCH_FAILURE'
export const MODULE_ITEMS_FETCH_CANCEL = 'MODULE_ITEMS_FETCH_CANCEL'

export const MODULE_ITEMS_BULK_INSERT = 'MODULE_ITEMS_BULK_INSERT'
