export const USER_DETAILS_FETCH = 'USER_DETAILS_FETCH'
export const USER_DETAILS_FETCH_SUCCESS = 'USER_DETAILS_FETCH_SUCCESS'
export const USER_DETAILS_FETCH_FAILURE = 'USER_DETAILS_FETCH_FAILURE'
export const USER_DETAILS_FETCH_CANCEL = 'USER_DETAILS_FETCH_CANCEL'
