export const ITEM_CONTENT_FETCH = 'ITEM_CONTENT_FETCH'
export const ITEM_CONTENT_FETCH_SUCCESS = 'ITEM_CONTENT_FETCH_SUCCESS'
export const ITEM_CONTENT_FETCH_FAILURE = 'ITEM_CONTENT_FETCH_FAILURE'
export const ITEM_CONTENT_FETCH_CANCEL = 'ITEM_CONTENT_FETCH_CANCEL'
