export const GRADES_FETCH = 'GRADES_FETCH'
export const GRADES_FETCH_SUCCESS = 'GRADES_FETCH_SUCCESS'
export const GRADES_FETCH_FAILURE = 'GRADES_FETCH_FAILURE'
export const GRADES_FETCH_CANCEL = 'GRADES_FETCH_CANCEL'
