export const RECORDINGS_FETCH = 'RECORDINGS_FETCH'
export const RECORDINGS_FETCH_SUCCESS = 'RECORDINGS_FETCH_SUCCESS'
export const RECORDINGS_FETCH_FAILURE = 'RECORDINGS_FETCH_FAILURE'
export const RECORDINGS_FETCH_CANCEL = 'RECORDINGS_FETCH_CANCEL'
