export const MODULES_FETCH = 'MODULES_FETCH'
export const MODULES_FETCH_SUCCESS = 'MODULES_FETCH_SUCCESS'
export const MODULES_FETCH_FAILURE = 'MODULES_FETCH_FAILURE'
export const MODULES_FETCH_CANCEL = 'MODULES_FETCH_CANCEL'
