export const COURSE_LIST_FETCH = 'COURSE_LIST_FETCH'
export const COURSE_LIST_FETCH_SUCCESS = 'COURSE_LIST_FETCH_SUCCESS'
export const COURSE_LIST_FETCH_FAILURE = 'COURSE_LIST_FETCH_FAILURE'
export const COURSE_LIST_FETCH_CANCEL = 'COURSE_LIST_FETCH_CANCEL'

export const COURSE_DETAILS_FETCH = 'COURSE_DETAILS_FETCH'
export const COURSE_DETAILS_FETCH_SUCCESS = 'COURSE_DETAILS_FETCH_SUCCESS'
export const COURSE_DETAILS_FETCH_FAILURE = 'COURSE_DETAILS_FETCH_FAILURE'
export const COURSE_DETAILS_FETCH_CANCEL = 'COURSE_DETAILS_FETCH_CANCEL'
