export const QUIZ_SUBMISSION_START = 'QUIZ_SUBMISSION_START'
export const QUIZ_SUBMISSION_START_SUCCESS = 'QUIZ_SUBMISSION_START_SUCCESS'
export const QUIZ_SUBMISSION_START_FAILURE = 'QUIZ_SUBMISSION_START_FAILURE'

export const QUIZ_SUBMISSION_COMPLETE = 'QUIZ_SUBMISSION_COMPLETE'
export const QUIZ_SUBMISSION_COMPLETE_SUCCESS =
  'QUIZ_SUBMISSION_COMPLETE_SUCCESS'
export const QUIZ_SUBMISSION_COMPLETE_FAILURE =
  'QUIZ_SUBMISSION_COMPLETE_FAILURE'

export const QUIZ_SUBMISSIONS_FETCH = 'QUIZ_SUBMISSIONS_FETCH'
export const QUIZ_SUBMISSIONS_FETCH_SUCCESS = 'QUIZ_SUBMISSIONS_FETCH_SUCCESS'
export const QUIZ_SUBMISSIONS_FETCH_FAILURE = 'QUIZ_SUBMISSIONS_FETCH_FAILURE'
export const QUIZ_SUBMISSIONS_FETCH_CANCEL = 'QUIZ_SUBMISSIONS_FETCH_CANCEL'
