export const QUIZ_QUESTIONS_FETCH = 'QUIZ_QUESTIONS_FETCH'
export const QUIZ_QUESTIONS_FETCH_SUCCESS = 'QUIZ_QUESTIONS_FETCH_SUCCESS'
export const QUIZ_QUESTIONS_FETCH_FAILURE = 'QUIZ_QUESTIONS_FETCH_FAILURE'

export const QUIZ_QUESTION_UPDATE_ANSWER = 'QUIZ_QUESTION_UPDATE_ANSWER'
export const QUIZ_QUESTION_FLAG = 'QUIZ_QUESTION_FLAG'
export const QUIZ_QUESTION_UNFLAG = 'QUIZ_QUESTION_UNFLAG'

export const QUIZ_SUBMISSION_ANSWERS_FETCH = 'QUIZ_SUBMISSION_ANSWERS_FETCH'
export const QUIZ_SUBMISSION_ANSWERS_FETCH_SUCCESS =
  'QUIZ_SUBMISSION_ANSWERS_FETCH_SUCCESS'
export const QUIZ_SUBMISSION_ANSWERS_FETCH_FAILURE =
  'QUIZ_SUBMISSION_ANSWERS_FETCH_FAILURE'

export const QUIZ_SUBMISSION_ANSWERS_SAVE = 'QUIZ_SUBMISSION_ANSWERS_SAVE'
export const QUIZ_SUBMISSION_ANSWERS_SAVE_SUCCESS =
  'QUIZ_SUBMISSION_ANSWERS_SAVE_SUCCESS'
export const QUIZ_SUBMISSION_ANSWERS_SAVE_FAILURE =
  'QUIZ_SUBMISSION_ANSWERS_SAVE_FAILURE'

export const QUIZ_LOG_EVENTS = 'QUIZ_LOG_EVENTS'
export const QUIZ_LOG_EVENTS_SUCCESS = 'QUIZ_LOG_EVENTS_SUCCESS'
export const QUIZ_LOG_EVENTS_FAILURE = 'QUIZ_LOG_EVENTS_FAILURE'
