export const INDUSTRY_ARTICLES_FETCH = 'INDUSTRY_ARTICLES_FETCH'
export const INDUSTRY_ARTICLES_FETCH_SUCCESS = 'INDUSTRY_ARTICLES_FETCH_SUCCESS'
export const INDUSTRY_ARTICLES_FETCH_FAILURE = 'INDUSTRY_ARTICLES_FETCH_FAILURE'
export const INDUSTRY_ARTICLES_FETCH_CANCEL = 'INDUSTRY_ARTICLES_FETCH_CANCEL'
